version: "2"

services:
    mongo:
        image: mongo:latest
        hostname: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongodata:/data/db
        networks:
            - network-reactive

    spring-reactive:
        build:
            context: ./
        image: spring-reactive
        environment:
            # Overrides the host in the Spring Boot application to use the Docker's hostname
            - SPRING_DATA_MONGODB_HOST=mongo
        ports:
            - "8080:8080"
        networks:
            - network-reactive

volumes:
    mongodata:

networks:
    network-reactive: